runtime: python311

env_variables:
  TOKEN: "gmail_agent_token"
  MY_NUMBER: "918328653599"

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

entrypoint: python main.py